SELECT TABLE_NAME, PARTITION_NAME, PARTITION_POSITION
FROM (SELECT TABLE_OWNER, TABLE_NAME, PARTITION_NAME, PARTITION_POSITION, rank()OVER(PARTITION BY TABLE_NAME ORDER BY PARTITION_POSITION DESC) partition_number FROM dba_tab_partitions)
WHERE partition_number IN (1, 2)
GROUP BY TABLE_NAME, PARTITION_NAME, PARTITION_POSITION
ORDER BY TABLE_NAME 
