-- HOW TO FIND THE  PARTITIONS IN ORACLE SQL FOR EVERY TABLE
-- THE WHERE CLAUSE IDENTIFIES THE POSITION OF THE PARTITION NUMBER FROM NEWER TO OLDER.
-- IF YOU WANT TO GET FOR SPECIFIC TABLES, ADD IN THE WHERE CLAUSE WHERE TABLE NAME IN (...).

SELECT TABLE_NAME, PARTITION_NAME, PARTITION_POSITION
FROM (SELECT TABLE_OWNER, TABLE_NAME, PARTITION_NAME, PARTITION_POSITION, rank()OVER(PARTITION BY TABLE_NAME ORDER BY PARTITION_POSITION DESC) partition_number FROM dba_tab_partitions)
WHERE partition_number IN (1, 2)
GROUP BY TABLE_NAME, PARTITION_NAME, PARTITION_POSITION
ORDER BY TABLE_NAME 
